networks:
  default:
    enable_ipv6: true
  web:
    external: true

services:
  postgres:
    image: postgres:14.16-alpine@sha256:f570e7807aa5387121c52f6457a195c39e95e4088040940d48212c77684ab0a2
    restart: always
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=(matrix_postgres_password)
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/fzr/matrix/postgresdata:/var/lib/postgresql/data:z
    networks:
      default:

  synapse:
    image: ghcr.io/element-hq/synapse:v1.124.0@sha256:e5f4232539203278eaef867496b99568c406b34208ed6f7a211e13c08c02373e
    container_name: synapse
    environment:
      - UID=991
      - GID=991
      - SYNAPSE_CONFIG_DIR=config
    restart: always
    configs:
      - source: synapse-homeserver
        target: /config/homeserver.yaml
        uid: "991"
        gid: "991"
      - source: synapse-log-config
        target: /config/log.config
        uid: "991"
        gid: "991"
    secrets:
      - source: matrix-signing-key
        target: signing.key
        uid: "991"
        gid: "991"
    volumes:
      - /home/fzr/matrix/media_store:/data/media_store:z
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      default:
      web:

  eturnal:
    image: ghcr.io/processone/eturnal:1.12.1-r2@sha256:8043d266f18838cb469a5289ac444a90b7a2aa8b8ab503155b81a2601618a33b
    userns_mode: host
    restart: always
    user: 0:0 # to access caddy certs
    environment:
      - ETURNAL_USER=root
    network_mode: host
    # ports:
    #   - '3478:3478'
    #   - '3478:3478/udp'
    #   - '49000-49200:49000-49200/udp'
    volumes:
      - caddy_data:/caddy-data:ro
    configs:
      - source: eturnal
        target: /etc/eturnal.yml

configs:
  synapse-homeserver:
    file: /home/fzr/matrix/homeserver.yaml
  synapse-log-config:
    file: /home/fzr/matrix/log.config
  eturnal:
    file: /home/fzr/matrix/eturnal.yml
secrets:
  matrix-signing-key:
    file: /home/fzr/matrix/signing.key #added by the create secrets step

volumes:
  caddy_data:
    external: true
