networks:
  default:
    enable_ipv6: true
  web:
    external: true

services:
  postgres:
    image: postgres:14.10-alpine@sha256:eff80106af6038ac29fa7a549f10ec02a56afa6a4a3afbe43de12bb3067e4cc5
    restart: always
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=(matrix_postgres_password)
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/ubuntu/matrix/postgresdata:/var/lib/postgresql/data
    networks:
      default:

  synapse:
    image: ghcr.io/element-hq/synapse:v1.98.0@sha256:491898f88803b54f3d50902fd25ed1a2f49b0fca70767a57d0dc117b57a83a0c
    container_name: synapse
    environment:
      - UID=991
      - GID=991
      - SYNAPSE_CONFIG_DIR=config
    restart: always
    configs:
      - source: synapse-homeserver
        target: /config/homeserver.yaml
        uid: "991"
        gid: "991"
      - source: synapse-log-config
        target: /config/log.config
        uid: "991"
        gid: "991"
    secrets:
      - source: matrix-signing-key
        target: signing.key
        uid: "991"
        gid: "991"
    volumes:
      - /home/ubuntu/matrix/media_store:/data/media_store:rw
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      default:
      web:

  eturnal:
    image: ghcr.io/processone/eturnal:edge@sha256:98631032de51691411ab7297df0f57b34363c41b2ffa2c66d4a9e9dab18cdd13
    userns_mode: host
    user: 0:0 # to access caddy certs
    environment:
      - ETURNAL_USER=root
    ports:
      - '3478:3478'
      - '3478:3478/udp'
      - '49000-49200:49000-49200/udp'
    volumes:
      - caddy_data:/caddy-data:ro
    configs:
      - source: eturnal
        target: /etc/eturnal.yml

  postgres-sync:
    image: postgres:15.5-alpine@sha256:ddaa3615f15a3d0ba9ef5f9af398d093fcce511fea1187049444fcd09626c21a
    restart: always
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=sync
      - POSTGRES_USER=sync
      - POSTGRES_PASSWORD=(matrix_syncv3_postgres_password)
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/ubuntu/matrix/postgresdata-sync:/var/lib/postgresql/data
    networks:
      default:

  sliding-sync:
    image: ghcr.io/matrix-org/sliding-sync:v0.99.13@sha256:38ff361a8deda98a146a5dbe48e38bad5060c37d62d1944b73ccfe391dc37582
    restart: always
    environment:
      - SYNCV3_SERVER=https://matrix.fariszr.com
      - SYNCV3_DB=(matrix_syncv3_postgres)
      - SYNCV3_SECRET="(matrix_syncv3_secret)"
    depends_on:
      - postgres-sync
      - synapse
    networks:
      web:
      default:


configs:
  synapse-homeserver:
    file: /home/ubuntu/matrix/homeserver.yaml
  synapse-log-config:
    file: /home/ubuntu/matrix/log.config
  eturnal:
    file: /home/ubuntu/matrix/eturnal.yml
secrets:
  matrix-signing-key:
    file: /home/ubuntu/matrix/signing.key #added by the create secrets step

volumes:
  caddy_data:
    external: true
