networks:
  default:
    enable_ipv6: true
  web:
    external: true

services:
  postgres:
    image: postgres:14.17-alpine@sha256:8430d17c310fe23e0b7dc930dad8b1020221f35a43545705b5dfad6ad40786d9
    restart: always
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=(matrix_postgres_password)
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/fzr/matrix/postgresdata:/var/lib/postgresql/data:z
    networks:
      default:

  synapse:
    image: ghcr.io/element-hq/synapse:v1.128.0@sha256:c3136780c55ea15bf1df44ffd48be1a151bbbb908f81ab768f6e20260a4d22a4
    container_name: synapse
    environment:
      - UID=991
      - GID=991
      - SYNAPSE_CONFIG_DIR=config
    restart: always
    configs:
      - source: synapse-homeserver
        target: /config/homeserver.yaml
        uid: "991"
        gid: "991"
      - source: synapse-log-config
        target: /config/log.config
        uid: "991"
        gid: "991"
    secrets:
      - source: matrix-signing-key
        target: signing.key
        uid: "991"
        gid: "991"
    volumes:
      - /home/fzr/matrix/media_store:/data/media_store:z
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      default:
      web:

  eturnal:
    image: ghcr.io/processone/eturnal:1.12.1-r2@sha256:8043d266f18838cb469a5289ac444a90b7a2aa8b8ab503155b81a2601618a33b
    userns_mode: host
    restart: always
    user: 0:0 # to access caddy certs
    environment:
      - ETURNAL_USER=root
    network_mode: host
    # ports:
    #   - '3478:3478'
    #   - '3478:3478/udp'
    #   - '49000-49200:49000-49200/udp'
    volumes:
      - caddy_data:/caddy-data:ro
    configs:
      - source: eturnal
        target: /etc/eturnal.yml

  # Added JWT Authentication Service for Element Call
  lk-jwt-service:
    image: ghcr.io/element-hq/lk-jwt-service:v0.2.2 # Pinning version
    container_name: element-call-jwt
    restart: unless-stopped
    environment:
      # Port the JWT service listens on internally
      - LK_JWT_PORT=8080
      # Publicly accessible URL for the LiveKit SFU WebSocket endpoint (updated domain)
      - LIVEKIT_URL=wss://matrixrtc.fariszr.com/livekit/sfu
      # API Key and Secret (must match LiveKit service and secrets)
      - LIVEKIT_KEY=(livekit_api_key)
      - LIVEKIT_SECRET=(livekit_api_secret)
      # Optional: Restrict call creation to users from specific homeservers
      - LIVEKIT_LOCAL_HOMESERVERS=fariszr.com # Hardcoded server name
    networks:
      default:
      web: # Needs to be reachable by Caddy

  livekit:
    image: livekit/livekit-server:v1.8.4 # Pinning to a specific version is recommended
    container_name: livekit
    # Use config file instead of just environment variables
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    # LIVEKIT_KEYS is still needed here for the server itself
    environment:
      - LIVEKIT_KEYS=(livekit_api_key):(livekit_api_secret)
      # Remove other env vars now handled by config.yaml
      # - LIVEKIT_WS_URL=wss://livekit.fariszr.com
      # - LIVEKIT_PORT=7880
    ports:
      # Port 7880 is now only needed internally for Caddy proxying to /livekit/sfu
      # - "7880:7880" # Client API and Webhook callback - No longer exposed directly
      - "7881:7881" # TURN/TLS (LiveKit's own TURN, though disabled in config)
      - "50100-50200:50100-50200/udp" # UDP port range for media over WebRTC
    volumes:
      # Mount the new config file
      - /home/fzr/matrix/livekit-config.yaml:/etc/livekit.yaml:ro
    networks:
      default:
      web: # Needs to be reachable by Caddy

configs:
  synapse-homeserver:
    file: /home/fzr/matrix/homeserver.yaml
  synapse-log-config:
    file: /home/fzr/matrix/log.config
  eturnal:
    file: /home/fzr/matrix/eturnal.yml

secrets:
  matrix-signing-key:
    file: /home/fzr/matrix/signing.key #added by the create secrets step

volumes:
  caddy_data:
    external: true
