networks:
  web:
    external: true
  default:
    enable_ipv6: true

services:
  etebase:
    image: victorrds/etebase:alpine@sha256:3c332face24e2e6127807e042890bbd3919a8bcc344aaacc4dbd45115182ccac
    container_name: "etebase"
    volumes:
      - /home/ubuntu/etesync/data:/data
      - /home/ubuntu/etesync/static:/srv/etebase/static:rw
    expose:
      - 3735
    environment:
      SERVER: uvicorn
      DB_ENGINE: postgres
      DATABASE_NAME: etebase
      DATABASE_USER: etebase
      DATABASE_PASSWORD: (ETESYNC_DB_PASS)
      DATABASE_HOST: postgres
      ALLOWED_HOSTS: (ETESYNC_DOMAIN)
      AUTO_UPDATE: true
    depends_on:
      - postgres
    restart: always
    networks:
      web:
      default:

  postgres:
    image: postgres:16-alpine@sha256:adf7f6c7a8ae301526a9c2ada2008e3ed9603c83400109215ef0b6798e60d1f9
    container_name: "postgres"
    volumes:
      - /home/ubuntu/etesync/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: (ETESYNC_DB_PASS)
      POSTGRES_USER: etebase
      POSTGRES_DB: etebase
    restart: always