networks:
  web:
    external: true
  default:
    enable_ipv6: true

services:
  etebase:
    image: victorrds/etebase:alpine@sha256:47a35dd707ffecb5d92756255ad92d1c07ffa287cced44a81c89607c41e45bca
    container_name: "etebase"
    volumes:
      - /home/ubuntu/etesync/data:/data
      - /home/ubuntu/etesync/static:/srv/etebase/static:rw
    expose:
      - 3735
    environment:
      SERVER: uvicorn
      DB_ENGINE: postgres
      DATABASE_NAME: etebase
      DATABASE_USER: etebase
      DATABASE_PASSWORD: (ETESYNC_DB_PASS)
      DATABASE_HOST: postgres
      ALLOWED_HOSTS: (ETESYNC_DOMAIN)
      AUTO_UPDATE: true
    depends_on:
      - postgres
    restart: always
    networks:
      web:
      default:

  postgres:
    image: postgres:16-alpine@sha256:492898505cb45f9835acc327e98711eaa9298ed804e0bb36f29e08394229550d
    container_name: "postgres"
    volumes:
      - /home/ubuntu/etesync/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: (ETESYNC_DB_PASS)
      POSTGRES_USER: etebase
      POSTGRES_DB: etebase
    restart: always