networks:
  web:
    external: true
  default:
    enable_ipv6: true

services:
  etebase:
    image: victorrds/etebase:alpine@sha256:47a35dd707ffecb5d92756255ad92d1c07ffa287cced44a81c89607c41e45bca
    container_name: "etebase"
    volumes:
      - /home/fzr/etesync/data:/data:z
      - /home/fzr/etesync/static:/srv/etebase/static:z
    expose:
      - 3735
    environment:
      SERVER: uvicorn
      DB_ENGINE: postgres
      DATABASE_NAME: etebase
      DATABASE_USER: etebase
      DATABASE_PASSWORD: (ETESYNC_DB_PASS)
      DATABASE_HOST: postgres
      ALLOWED_HOSTS: (ETESYNC_DOMAIN)
      AUTO_UPDATE: true
    depends_on:
      - postgres
    restart: always
    networks:
      web:
      default:

  postgres:
    image: postgres:16-alpine@sha256:d898b0b78a2627cb4ee63464a14efc9d296884f1b28c841b0ab7d7c42f1fffdf
    container_name: "postgres"
    volumes:
      - /home/fzr/etesync/postgres/data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: (ETESYNC_DB_PASS)
      POSTGRES_USER: etebase
      POSTGRES_DB: etebase
    restart: always