name: deploy-etesync

on:
  push:
    paths:
      - '.github/workflows/etesync.yml'
      - 'etesync/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4d
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_SECRET }}
          tags: tag:deploy-ci
          hostname: Github-actions
          version: ${{ vars.TAILSCALE_VERSION }}

      # allows for quicker local debugging
      - name: Add secrets to docker-compose.yml
        env:
          ETESYNC_DOMAIN: ${{ secrets.ETESYNC_DOMAIN }}
          ETESYNC_DB_PASS: ${{ secrets.ETESYNC_DB_PASS }}
        run: |
          sed -i "s|(ETESYNC_DOMAIN)|$ETESYNC_DOMAIN|g" $GITHUB_WORKSPACE/etesync/docker-compose.yml
          sed -i "s|(ETESYNC_DB_PASS)|$ETESYNC_DB_PASS|g" $GITHUB_WORKSPACE/etesync/docker-compose.yml

      - name: Start Deployment
        uses: FarisZR/docker-compose-gitops-action@v1.0.1
        with:
          remote_docker_host: ${{ secrets.server_address }}
          tailscale_ssh: true # no need for manual private and public keys
          compose_file_path: etesync/docker-compose.yml
          args: -p etesync up -d --remove-orphans
          upload_directory: true
          docker_compose_directory: etesync