name: deploy-etesync

on:
  push:
    paths:
      - '.github/workflows/etesync.yml'
      - 'etesync/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # allows for quicker local debugging
      - name: Add secrets to docker-compose.yml
        env:
          ETESYNC_DOMAIN: ${{ secrets.ETESYNC_DOMAIN }}
          ETESYNC_DB_PASS: ${{ secrets.ETESYNC_DB_PASS }}
        run: |
          sed -i "s|(ETESYNC_DOMAIN)|$ETESYNC_DOMAIN|g" $GITHUB_WORKSPACE/etesync/docker-compose.yml
          sed -i "s|(ETESYNC_DB_PASS)|$ETESYNC_DB_PASS|g" $GITHUB_WORKSPACE/etesync/docker-compose.yml

      - name: Start Deployment
        uses: FarisZR/docker-compose-gitops-action@v1.0.1
        with:
          remote_docker_host: ${{ secrets.server_address }}
          ssh_public_key: ${{ secrets.public_ssh_key }}
          ssh_private_key: ${{ secrets.private_ssh_key }}
          compose_file_path: etesync/docker-compose.yml
          args: -p etesync up -d --remove-orphans
          upload_directory: true
          docker_compose_directory: etesync