name: deploy-matrix

on:
  push:
    paths:
      - '.github/workflows/matrix.yml'
      - 'matrix/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Matrix
      url: https://matrix.fariszr.com
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add secrets to homeserver.yml
        env:
          MATRIX_TURN_SHARED_SECRET: ${{ secrets.matrix_turn_shared_secret }}
          MATRIX_REGISTRATION_SHARED_SECRET: ${{ secrets.matrix_registration_shared_secret }}
          MATRIX_MACAROON_SECRET_KEY: ${{ secrets.matrix_macaroon_secret_key }}
          MATRIX_FORM_SECRET: ${{ secrets.matrix_form_secret }}
          MATRIX_POSTGRES_PASSWORD: ${{ secrets.matrix_postgres_password }}
          SMTP_PASSWORD: ${{ secrets.smtp_password }}
          SMTP_USERNAME: ${{ secrets.smtp_username }}
          SMTP_ENDPOINT: ${{ secrets.smtp_endpoint }}
          MATRIX_SMTP_FROM_ADDRESS: ${{ secrets.matrix_smtp_from_address }}
        run: |
          sed -i "s|(matrix_turn_shared_secret)|$MATRIX_TURN_SHARED_SECRET|g" $GITHUB_WORKSPACE/matrix/homeserver.yaml
          sed -i "s|(matrix_registration_shared_secret)|$MATRIX_REGISTRATION_SHARED_SECRET|g" $GITHUB_WORKSPACE/matrix/homeserver.yaml
          sed -i "s|(matrix_macaroon_secret_key)|$MATRIX_MACAROON_SECRET_KEY|g" $GITHUB_WORKSPACE/matrix/homeserver.yaml
          sed -i "s|(matrix_form_secret)|$MATRIX_FORM_SECRET|g" $GITHUB_WORKSPACE/matrix/homeserver.yaml
          sed -i "s|(matrix_postgres_password)|$MATRIX_POSTGRES_PASSWORD|g" $GITHUB_WORKSPACE/matrix/homeserver.yaml
          sed -i "s|(smtp_password)|$SMTP_PASSWORD|g" $GITHUB_WORKSPACE/matrix/homeserver.yaml
          sed -i "s|(smtp_username)|$SMTP_USERNAME|g" $GITHUB_WORKSPACE/matrix/homeserver.yaml
          sed -i "s|(smtp_endpoint)|$SMTP_ENDPOINT|g" $GITHUB_WORKSPACE/matrix/homeserver.yaml
          sed -i "s|(matrix_smtp_from_address)|$MATRIX_SMTP_FROM_ADDRESS|g" $GITHUB_WORKSPACE/matrix/homeserver.yaml

      - name: Add secrets to eturnal.yml
        env:
          MATRIX_TURN_SHARED_SECRET: ${{ secrets.matrix_turn_shared_secret }}
        run: |
          sed -i "s|(matrix_turn_shared_secret)|$MATRIX_TURN_SHARED_SECRET|g" $GITHUB_WORKSPACE/matrix/eturnal.yml

      - name: Add secrets to docker-compose.yml
        env:
          MATRIX_POSTGRES_PASSWORD: ${{ secrets.matrix_postgres_password }}
        run: |
          sed -i "s|(matrix_postgres_password)|$MATRIX_POSTGRES_PASSWORD|g" $GITHUB_WORKSPACE/matrix/docker-compose.yml


      - name: Create Secrets
        env:
          MATRIX_SIGNING_KEY: ${{ secrets.MATRIX_SIGNING_KEY }}
        run: |
          touch $GITHUB_WORKSPACE/matrix/signing.key
          echo "$MATRIX_SIGNING_KEY" > "$GITHUB_WORKSPACE/matrix/signing.key"

      - name: Start Deployment
        uses: FarisZR/docker-compose-gitops-action@v1.1
        env:
          POSTGRES_PASSWORD: ${{ secrets.matrix_postgres_password }}
          MATRIX_SIGNING_KEY: ${{ secrets.matrix_signing_key }}
        with:
          remote_docker_host: ${{ secrets.server_address }}
          ssh_public_key: ${{ secrets.public_ssh_key }}
          ssh_private_key: ${{ secrets.private_ssh_key }}
          compose_file_path: matrix/docker-compose.yml
          args: -p matrix up -d --remove-orphans
          upload_directory: true
          docker_compose_directory: matrix