name: deploy-radicale

on:
  push:
    paths:
      - '.github/workflows/radicale.yml'
      - 'radicale/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: radicale
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4d
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_SECRET }}
          tags: tag:deploy-ci
          hostname: Github-actions
          version: ${{ vars.TAILSCALE_VERSION }}

      - name: Create Secrets
        env:
          RADICALE_HTPASSWD: ${{ secrets.radicale_htpasswd }}
        run: |
          touch $GITHUB_WORKSPACE/radicale/htpasswd
          echo "$RADICALE_HTPASSWD" > "$GITHUB_WORKSPACE/radicale/htpasswd"

      - name: Start Deployment
        uses: FarisZR/docker-compose-gitops-action@v1.0.1
        with:
          remote_docker_host: ${{ secrets.server_address }}
          tailscale_ssh: true # no need for manual private and public keys
          compose_file_path: radicale/docker-compose.yml
          args: -p radicale up -d --remove-orphans
          upload_directory: true
          docker_compose_directory: radicale